### ISSUE TITLE
error: ‘TheiaTool’ was not declared in this scope  

### ISSUE THREAD

**Issue by Sunshinehualong** [AnshanTJU/FILD#4]
Hi~
when I compiled the project,  had the error:
`
FILD/loop-closure-detection/src/lcdengine.cpp:87:5: error: ‘TheiaTool’ was not declared in this scope  TheiaTool theia(dim); 
`
I find in the  "theialib.hpp"
I don't have the file of  /export/cheguangfu/Items/theialib/include/theialib.hpp

could you help me to solve this problem?

**Comment by AnshanTJU** [comment]
Hi, the hnswlib and the theialib are added in the repo. You can use them to compile the project.

**Comment by Sunshinehualong** [comment]
Thanks!
